version: '3.8'

services:
  ktor-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 99208834
      POSTGRES_DB: movie_pub_db
    ports:
      - "5432:5432"